version: "3"
services:
  hadoop-master:
    build: .
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870" # HDFS Web UI
      - "8088:8088" # YARN Web UI
      - "8080:8080" # Spark Master Web UI
    environment:
      - HADOOP_HOME=/usr/local/hadoop
      - SPARK_MASTER_HOST=hadoop-master
    networks:
      - hadoop-net

  hadoop-worker1:
    build: .
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    environment:
      - SPARK_MASTER_HOST=hadoop-master
    networks:
      - hadoop-net

  hadoop-worker2:
    build: .
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    environment:
      - SPARK_MASTER_HOST=hadoop-master
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge